#! /usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_concert/license/LICENSE
#
##############################################################################
# Imports
##############################################################################

import rospkg
import rospy
from concert_service_manager import ServiceManager
from concert_service_manager import InvalidSolutionConfigurationException, InvalidServiceProfileException

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    rospy.init_node('service_manager')
    try:
        sm = ServiceManager()
        sm.spin()
    except (rospkg.ResourceNotFound, InvalidSolutionConfigurationException, InvalidServiceProfileException) as e:
        rospy.logerr("Service Manager : %s" % str(e))
        raise e
