#! /usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_concert/license/LICENSE
#
##############################################################################
# Imports
##############################################################################

import rospy
from concert_service_manager import ServiceManager

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    rospy.init_node('service_manager')
    sm = ServiceManager()
    sm.spin()
