#!/usr/bin/env python
#       
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_app_manager/concert_conductor/LICENSE
#
import rospy
import concert_scheduler

if __name__ == '__main__':
    rospy.init_node('scheduler')
    scheduler = concert_scheduler.ConcertScheduler()
    scheduler.spin()
