#!/usr/bin/env python
#       
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_multimaster/master/rocon_gateway/LICENSE 
#

##############################################################################
# Imports
##############################################################################

import sys
import argparse
import rospy
#import re
#import itertools
#import rocon_utilities
import rocon_utilities.console as console
import concert_msgs.srv as concert_srvs
import rocon_std_msgs.msg as rocon_std_msgs

##############################################################################
# Globals
##############################################################################

service_name = '/concert/get_roles_and_apps'

##############################################################################
# Functions
##############################################################################
    
def parse_arguments():
    parser = argparse.ArgumentParser(description='Prettifies concert roles and apps information.')
    args = parser.parse_args()
    return args


##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    
    rospy.init_node('roles_and_apps')
    args = parse_arguments()
    get_roles_and_apps = rospy.ServiceProxy(service_name, concert_srvs.GetRolesAndApps)
    request = concert_srvs.GetRolesAndAppsRequest()
    request.roles = []
    request.platform_info = rocon_std_msgs.PlatformInfo(
                            os='*',
                            version='*',
                            system='*',
                            platform='*'
                            )
    response = get_roles_and_apps(request)
    for d in response.data:
        console.pretty_println("%s" % d.role, console.bold)
        for remocon_app in d.remocon_apps:
            console.pretty_println("  %s" % remocon_app.display_name, console.green)
            print(console.cyan + "    Name" + console.reset + "       : " + console.yellow + "%s" % remocon_app.name + console.reset)
            print(console.cyan + "    Description" + console.reset + ": " + console.yellow + "%s" % remocon_app.description + console.reset)
            for remapping in remocon_app.remappings:
                print(console.cyan + "    Remapping" + console.reset + "  : " + console.yellow + "%s->%s" % (remapping.remap_from, remapping.remap_to) + console.reset)
            for parameter in remocon_app.parameters:
                print(console.cyan + "    Parameter" + console.reset + "  : " + console.yellow + "[%s, %s]" % (parameter.key, parameter.value) + console.reset)
