#!/usr/bin/env python
#       
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_multimaster/master/rocon_gateway/LICENSE 
#

##############################################################################
# Imports
##############################################################################

import os
import sys
import argparse
import rospy
import rocon_utilities
import concert_roles

##############################################################################
# Functions
##############################################################################
    
def parse_arguments():
    parser = argparse.ArgumentParser(description='Load a list of roles and apps from yaml')
    parser.add_argument('package', type=str, help="package containing the yaml file")
    parser.add_argument('yaml', type=str, help="yaml filename")
    parser.add_argument('-s', '--service-name', action='store',
                   default='Cybernetic Piracy',
                   help='service that is loading the role-app table [Cybernetic Piracy]')
    myargs = rospy.myargv(argv=sys.argv)
    args = parser.parse_args(args=myargs[1:])
    if os.path.splitext(args.yaml)[-1] == '':  # no ext given
        args.yaml = args.yaml + ".yaml"
    return args

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    rospy.init_node('roles_and_apps')
    try:
        role_app_loader = concert_roles.RoleAppLoader()
    except rospy.exceptions.ROSException as e:
        rospy.logerr("Role Loader : aborting, %s." % str(e))
        sys.exit(1)
    except rospy.exceptions.ROSInterruptException as e:
        sys.exit(1)
    args = parse_arguments()
    try:
        role_app_loader.load(args.package + '/' + args.yaml, args.service_name)
    except rocon_utilities.exceptions.ResourceNotFoundException as e:
        rospy.logerr("Role Loader : %s." % str(e))
        sys.exit(1)
    except concert_roles.exceptions.InvalidRoleAppYaml as e:
        rospy.logwarn("Role Loader : %s" % str(e))
        sys.exit(1)
